name: med_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3 # Check for the latest version
  shared_preferences: ^2.0.0
  timezone: ^ 

  
  flutter_local_notifications: 
  flutter_localizations:
    sdk: flutter  # Correctly indented

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/medicine_icon.svg